### ISSUE TITLE
No sound on loudspeaker

### ISSUE THREAD

**Issue by tvardero** [PixelExperience-Devices/device_xiaomi_begonia#1]
**What happened?**
Suddenly, loud speaker had stopped working while watching youtube video (so it was working for a while). Reboot didn't help with the situation. Music app - same problem.
Also had noticed today that ringtone plays for 2-5 seconds, but not any more.
Sound in earspeaker and/or BT headset is OK.
*UPDATE:* scrolling in music fixed the problem, but it might appear again.

**Device**
PE 20200823 1919 OFFICIAL
Xiaomi Redmi Note 8 Pro (begonia)
Vendor Q MIUI 11 Global, CFR v2
Magisk 20.3, magisk modules: ANX camera v190

**Logcat**
[no_sound.txt](https://github.com/PixelExperience-Devices/device_xiaomi_begonia/files/5125629/no_sound.txt)

**Comment by tvardero** [comment]
dmesg will be sent as soon, as i catch this bug again

**Comment by ZIDAN44** [comment]
Ok.. I will check soon

**Comment by tvardero** [comment]
**dmesg log**
(cathed bug only today, sorry, so late)
[dmesg.log](https://github.com/PixelExperience-Devices/device_xiaomi_begonia/files/5140636/dmesg.log)

**Comment by tvardero** [comment]
**Little update on bug information**
Any sound doesn't emit from loudspeaker. Reboot does not help, power off -> on does not help, clearing either dalvik or cache does not help.

Bug appear without any reasons or after specific event or user action, it appears suddenly in middle of video/audio playback. And holds for a while, but everytime nearly an half an hour.

Logcat and dmesg are up above. 

Scrolling music back and forth does NOT help.

**Comment by tvardero** [comment]
It was a physical damage to device (water damage), sorry for inconvenience.

**Comment by ZIDAN44** [comment]
NP
